---
- name: Deploy container
  community.general.proxmox:
    api_user: '{{ proxmox_user }}'
    api_password: '{{ proxmox_password }}'
    api_host: '{{ proxmox_host }}'
    password: '{{ proxmox_default_password }}'
    node: '{{ proxmox_node }}'
    hostname: '{{ inventory_hostname_short }}'
    ostemplate: '{{ proxmox_ostemplate }}'
    disk: '{{ proxmox_disk }}'
    cores: '{{ proxmox_cores }}'
    memory: '{{ proxmox_memory }}'
    swap: '{{ proxmox_memory }}'
    onboot: '{{ proxmox_onboot }}'
    pubkey: '{{ proxmox_pubkey }}'
    unprivileged: true
    features:
      - nesting=1
    netif: '{"net0":"name=eth0,gw={{ proxmox_gateway }},ip={{ proxmox_ip }}{{ proxmox_netmask }},bridge=vmbr0"}'
    state: present
  notify:
    - Start container
  delegate_to: localhost
...
