---
- name: Deploy container
  community.general.proxmox:
    api_user: '{{ proxmox_user }}'
    api_password: '{{ proxmox_password }}'
    api_host: '{{ proxmox_host }}'
    password: "{{ lookup('ansible.builtin.password', '/dev/null') }}"
    node: '{{ proxmox_node }}'
    hostname: '{{ inventory_hostname }}'
    ostemplate: '{{ proxmox_ostemplate }}'
    state: present
  delegate_to: localhost
...
