---
- name: Start container
  community.general.proxmox:
    api_user: '{{ proxmox_user }}'
    api_password: '{{ proxmox_password }}'
    api_host: '{{ proxmox_host }}'
    node: '{{ proxmox_node }}'
    hostname: '{{ inventory_hostname_short }}'
    unprivileged: true
    state: started
  register: start_result
  retries: 6
  delay: 10
  until: start_result is succeeded
  delegate_to: localhost
...
